server {
  listen 80;
  root /usr/share/nginx/html;

  # los archivos con huella en el nombre se pueden guardar en cache sin miedo
  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location / {
    add_header Cache-Control "no-cache";
    try_files $uri /index.html;
  }
}
